nats_url: "nats://localhost:4222" # Default NATS server URL
server_addr: ":8080" # HTTP server listen address
metrics_addr: ":9090" # Prometheus metrics listen address
request_timeout_seconds: 30 # Timeout for waiting NATS response
nats_stream: "TASK" # JetStream stream name

routes:
  - path: "/hello/" # Note trailing slash might matter depending on router
    methods: ["POST"]
    service: "hello"

  - path: "/goodbye"
    methods: ["GET"]
    service: "goodbye"
