nats_url: "nats://localhost:4222" # Default NATS server URL
server_addr: ":8080" # HTTP server listen address
metrics_addr: ":9090" # Prometheus metrics listen address
request_timeout_seconds: 30 # Timeout for waiting NATS response

routes:
  - path: "/hello/" # Note trailing slash might matter depending on router
    method: "POST"
    nats_stream: "ORDERS" # JetStream stream name
    nats_subject: "tasks.ORDERS.hello" # CHANGED: Subject now matches tasks.ORDERS.*

  - path: "/goodbye"
    method: "GET"
    nats_stream: "ORDERS" # Can reuse streams
    nats_subject: "tasks.ORDERS.goodbye"
